openapi: 3.0.3
info:
  title: Flight Data Management API
  description: |
    RESTful API for managing flight data with support for CRUD operations 
    and integration with external suppliers like CrazySupplier.
  version: 1.0.0
  contact:
    name: Vítor Matosinho Martins
    email: support@flightdata.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.flightdata.com
    description: Production server

tags:
  - name: Flights
    description: Flight data management operations

paths:
  /api/v1/flights:
    get:
      tags:
        - Flights
      summary: Search and filter flights
      description: Retrieve flights based on search criteria from both database and external suppliers
      operationId: searchFlights
      parameters:
        - name: origin
          in: query
          description: 3-letter departure airport code
          required: false
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
            example: JFK
        - name: destination
          in: query
          description: 3-letter destination airport code
          required: false
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
            example: LAX
        - name: airline
          in: query
          description: Airline name
          required: false
          schema:
            type: string
            example: American Airlines
        - name: departureFrom
          in: query
          description: Minimum departure time (ISO 8601 format)
          required: false
          schema:
            type: string
            format: date-time
            example: '2025-10-24T10:00:00Z'
        - name: departureTo
          in: query
          description: Maximum departure time (ISO 8601 format)
          required: false
          schema:
            type: string
            format: date-time
            example: '2025-10-24T18:00:00Z'
        - name: arrivalFrom
          in: query
          description: Minimum arrival time (ISO 8601 format)
          required: false
          schema:
            type: string
            format: date-time
            example: '2025-10-24T13:00:00Z'
        - name: arrivalTo
          in: query
          description: Maximum arrival time (ISO 8601 format)
          required: false
          schema:
            type: string
            format: date-time
            example: '2025-10-24T21:00:00Z'
        - name: page
          in: query
          description: Page number (0-indexed)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightSearchResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Flights
      summary: Create a new flight
      description: Add a new flight record to the database
      operationId: createFlight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightCreateRequest'
      responses:
        '201':
          description: Flight created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/flights/{id}:
    get:
      tags:
        - Flights
      summary: Get flight by ID
      description: Retrieve a specific flight by its ID
      operationId: getFlightById
      parameters:
        - name: id
          in: path
          required: true
          description: Flight ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightResponse'
        '404':
          description: Flight not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Flights
      summary: Update flight
      description: Update an existing flight record
      operationId: updateFlight
      parameters:
        - name: id
          in: path
          required: true
          description: Flight ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightUpdateRequest'
      responses:
        '200':
          description: Flight updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Flight not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Flights
      summary: Delete flight
      description: Delete a flight record
      operationId: deleteFlight
      parameters:
        - name: id
          in: path
          required: true
          description: Flight ID
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Flight deleted successfully
        '404':
          description: Flight not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    FlightCreateRequest:
      type: object
      required:
        - airline
        - supplier
        - fare
        - departureAirport
        - destinationAirport
        - departureTime
        - arrivalTime
      properties:
        airline:
          type: string
          description: Airline name
          example: American Airlines
          minLength: 1
          maxLength: 100
        supplier:
          type: string
          description: Supplier providing the flight data
          example: GlobalSupplier
          minLength: 1
          maxLength: 100
        fare:
          type: number
          format: double
          description: Total price of the flight
          example: 299.99
          minimum: 0
        departureAirport:
          type: string
          description: 3-letter departure airport code
          pattern: '^[A-Z]{3}$'
          example: JFK
        destinationAirport:
          type: string
          description: 3-letter destination airport code
          pattern: '^[A-Z]{3}$'
          example: LAX
        departureTime:
          type: string
          format: date-time
          description: Departure time in ISO 8601 format (UTC)
          example: '2025-10-24T10:30:00Z'
        arrivalTime:
          type: string
          format: date-time
          description: Arrival time in ISO 8601 format (UTC)
          example: '2025-10-24T16:45:00Z'

    FlightUpdateRequest:
      type: object
      properties:
        airline:
          type: string
          description: Airline name
          example: American Airlines
          minLength: 1
          maxLength: 100
        supplier:
          type: string
          description: Supplier providing the flight data
          example: GlobalSupplier
          minLength: 1
          maxLength: 100
        fare:
          type: number
          format: double
          description: Total price of the flight
          example: 299.99
          minimum: 0
        departureAirport:
          type: string
          description: 3-letter departure airport code
          pattern: '^[A-Z]{3}$'
          example: JFK
        destinationAirport:
          type: string
          description: 3-letter destination airport code
          pattern: '^[A-Z]{3}$'
          example: LAX
        departureTime:
          type: string
          format: date-time
          description: Departure time in ISO 8601 format (UTC)
          example: '2025-10-24T10:30:00Z'
        arrivalTime:
          type: string
          format: date-time
          description: Arrival time in ISO 8601 format (UTC)
          example: '2025-10-24T16:45:00Z'

    FlightResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique flight identifier
          example: 1
        airline:
          type: string
          description: Airline name
          example: American Airlines
        supplier:
          type: string
          description: Supplier providing the flight data
          example: GlobalSupplier
        fare:
          type: number
          format: double
          description: Total price of the flight
          example: 299.99
        departureAirport:
          type: string
          description: 3-letter departure airport code
          example: JFK
        destinationAirport:
          type: string
          description: 3-letter destination airport code
          example: LAX
        departureTime:
          type: string
          format: date-time
          description: Departure time in ISO 8601 format (UTC)
          example: '2025-10-24T10:30:00Z'
        arrivalTime:
          type: string
          format: date-time
          description: Arrival time in ISO 8601 format (UTC)
          example: '2025-10-24T16:45:00Z'

    FlightSearchResponse:
      type: object
      properties:
        flights:
          type: array
          items:
            $ref: '#/components/schemas/FlightResponse'
        pagination:
          $ref: '#/components/schemas/PaginationInfo'

    PaginationInfo:
      type: object
      properties:
        currentPage:
          type: integer
          example: 0
        pageSize:
          type: integer
          example: 20
        totalElements:
          type: integer
          format: int64
          example: 100
        totalPages:
          type: integer
          example: 5

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: '2025-10-24T10:30:00Z'
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: Invalid airport code format
        path:
          type: string
          example: /api/v1/flights